### ISSUE TITLE
Continuos Integration Tool

### ISSUE THREAD

**Issue by guilhermeddf** [Eynorey/SAM#2]
Does this project use any Continuous Integration Tool? If so, is it online? (TravisCI, CircleCI), or offline tool (Jenkins, Hudson).

**Comment by thedomdom** [comment]
Hi Guilherme, we used Azure for continuous integration (online).

**Comment by Eynorey** [comment]
The CI capabilities of Visual Studio Team Services (VSTS) to be precise

**Comment by guilhermeddf** [comment]
Thank you guys!
